//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud_operations.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Categoryid { get; set; }
        public string Description { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public bool IsAvaliable { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
